### ISSUE TITLE
Prebuilt binaries crash on clean install Fedora Cinnamon edition

### ISSUE THREAD

**Issue by kogiokka** [copperspice/copperspice#146]
I think it's more like a packaging problem, but since it happens to both KitchenSink and Diamond editor I'll put the issue here.

Here is the stack trace of prebuilt KS on a clean install Fedora Cinnamon 31 machine.
```

(gdb) run
Starting program: /home/luis/Documents/KS/kitchensink 
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.30-11.fc31.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Unable to load library /home/luis/Documents/KS/platforms/CsGuiXcb1.6.so: (No such file or directory)
The application failed to start because the platform plugin was not found or did not load.
Requested Plugin Key: "xcb"

Reinstalling the application may resolve this problem.

Program received signal SIGABRT, Aborted.
0x00007ffff2ba0625 in raise () from /lib64/libc.so.6
(gdb) where
#0  0x00007ffff2ba0625 in raise () from /lib64/libc.so.6
#1  0x00007ffff2b898d9 in abort () from /lib64/libc.so.6
#2  0x00007ffff331f05a in qt_message_output(QtMsgType, Cs::QStringView<QString8>) [clone .cold] () from /home/luis/Documents/KS/libCsCore1.6.so
#3  0x00007ffff33f2f7c in qt_message(QtMsgType, char const*, __va_list_tag*) () from /home/luis/Documents/KS/libCsCore1.6.so
#4  0x00007ffff33f38c7 in qFatal(char const*, ...) () from /home/luis/Documents/KS/libCsCore1.6.so
#5  0x00007ffff4d8edd5 in init_platform(QString8 const&, QString8 const&, QString8 const&, int&, char**) () from /home/luis/Documents/KS/libCsGui1.6.so
#6  0x00007ffff4d8fbbe in QApplicationPrivate::createPlatformIntegration() () from /home/luis/Documents/KS/libCsGui1.6.so
#7  0x00007ffff4d90b78 in QApplicationPrivate::createEventDispatcher() () from /home/luis/Documents/KS/libCsGui1.6.so
#8  0x00007ffff34dd64b in QCoreApplicationPrivate::init() () from /home/luis/Documents/KS/libCsCore1.6.so
#9  0x00007ffff4d956ee in QApplicationPrivate::init() () from /home/luis/Documents/KS/libCsGui1.6.so
#10 0x00007ffff4d97544 in QApplication::QApplication(int&, char**, int) () from /home/luis/Documents/KS/libCsGui1.6.so
#11 0x0000000000489191 in main ()
(gdb) 
```

**Comment by kogiokka** [comment]
```
[luis@localhost Documents]$ ldd platforms/CsGuiXcb1.6.so 
ldd: warning: you do not have execution permission for `platforms/CsGuiXcb1.6.so'
	linux-vdso.so.1 (0x00007ffd4a98a000)
	libCsGui1.6.so => not found
	libfontconfig.so.1 => /lib64/libfontconfig.so.1 (0x00007f46f0504000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00007f46f04d9000)
	libxcb-image.so.0 => not found
	libxcb-icccm.so.4 => not found
	libxcb-sync.so.1 => /lib64/libxcb-sync.so.1 (0x00007f46f04cf000)
	libxcb-xfixes.so.0 => /lib64/libxcb-xfixes.so.0 (0x00007f46f04c3000)
	libxcb-shm.so.0 => /lib64/libxcb-shm.so.0 (0x00007f46f04be000)
	libxcb-randr.so.0 => /lib64/libxcb-randr.so.0 (0x00007f46f04ab000)
	libxcb-shape.so.0 => /lib64/libxcb-shape.so.0 (0x00007f46f04a6000)
	libxcb-keysyms.so.1 => not found
	libxcb-xinerama.so.0 => /lib64/libxcb-xinerama.so.0 (0x00007f46f04a1000)
	libxcb-xkb.so.1 => /lib64/libxcb-xkb.so.1 (0x00007f46f0480000)
	libxcb-render.so.0 => /lib64/libxcb-render.so.0 (0x00007f46f0470000)
	libxcb-render-util.so.0 => not found
	libSM.so.6 => /lib64/libSM.so.6 (0x00007f46f0465000)
	libICE.so.6 => /lib64/libICE.so.6 (0x00007f46f0447000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00007f46f0301000)
	libXi.so.6 => /lib64/libXi.so.6 (0x00007f46f02ed000)
	libX11-xcb.so.1 => /lib64/libX11-xcb.so.1 (0x00007f46f02e8000)
	libxkbcommon.so.0 => /lib64/libxkbcommon.so.0 (0x00007f46f02a5000)
	libxkbcommon-x11.so.0 => /lib64/libxkbcommon-x11.so.0 (0x00007f46f029a000)
	libCsCore1.6.so => not found
	libz.so.1 => /lib64/libz.so.1 (0x00007f46f0280000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f46f0277000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f46f0255000)
	libOpenGL.so.0 => /lib64/libOpenGL.so.0 (0x00007f46f0224000)
	libGLX.so.0 => /lib64/libGLX.so.0 (0x00007f46f01f0000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f46efff7000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f46efeb1000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f46efe95000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f46efccc000)
	libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007f46efc0b000)
	libexpat.so.1 => /lib64/libexpat.so.1 (0x00007f46efbdd000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00007f46efbd7000)
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00007f46efbcb000)
	libXext.so.6 => /lib64/libXext.so.6 (0x00007f46efbb6000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f46f0672000)
	libGLdispatch.so.0 => /lib64/libGLdispatch.so.0 (0x00007f46efaf9000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f46efae5000)
	libpng16.so.16 => /lib64/libpng16.so.16 (0x00007f46efaaf000)
```

So after I install the missing packages,  KS runs without issues.
Here is the full list of the missing dependencies on Fedora Cinnamon:
```
dnf install  mesa-libGL-devel \
xcb-util-wm \
xcb-util-image \
xcb-util-keysyms \
xcb-util-renderutil
```

**Comment by kogiokka** [comment]
Is it possible to include all this into the prebuilt binaries? If not there might also mention the requirements on the intro page of KS.

**Comment by vdeurzen** [comment]
@kogiokka I don't think we should link with these particular libraries statically (I'm also not sure that would be possible, but I haven't looked into it). Providing the libraries as dynamic libraries is something we could look into, however, this would put a maintenance burden on our packaging set-up to ensure compatibility with the user's system for each configuration and supported system.

I will make sure we have a look at the documentation and discuss adding the necessary information to those pages with the team.

Thank you again for helping us debug this, this is very valuable and I appreciate it a lot!

**Comment by agserm** [comment]
It is not feasible for us to supply the required packages for every platform. We do, however, have a well published and maintained list of dependencies in our documentation, as Tim provided. We believe the optimal solution is to supply an RPM package which would automatically install all required dependencies. Pull requests for this feature would be very welcome.

**Comment by agserm** [comment]
Closing since this issue is actually a result of missing dependencies, not a CopperSpice or KitchenSink problem.
